# -*- coding: utf-8 -*-
"""
知识点索引：整个项目拆解成「归属清晰、出处明确」的一条条知识点。

每个知识点都带：
    layer  —— 归属：arch(整体架构) / frontend(前端) / backend(后端) / database(数据库) / recommend(推荐系统)
    source —— 源码出处（文件名:行号），学习者可以直接翻到对应位置对照
    demo   —— 前端知识点额外挂一个可运行 HTML（在 learn/static/demos/ 下）
    level  —— 难度：入门 / 进阶 / 实战

行号基于当前版本源码，如果项目后续改动可能会有偏移。
"""

from typing import Any, Dict, List

# 每个 layer 的颜色前端用来渲染归属标签
LAYER_META: Dict[str, Dict[str, str]] = {
    "arch": {"name": "整体架构", "color": "#6b46c1", "desc": "前后端数据库怎么串起来"},
    "frontend": {"name": "前端", "color": "#3b6cf6", "desc": "浏览器里跑的部分"},
    "backend": {"name": "后端", "color": "#0f9d58", "desc": "服务器上的 Python 代码"},
    "database": {"name": "数据库", "color": "#e8710a", "desc": "SQLite 里的数据与 SQL"},
    "recommend": {"name": "推荐系统", "color": "#c5221f", "desc": "召回、排序、评估"},
}

CHAPTERS: List[Dict[str, Any]] = [
    # ============================================================ 第 0 章
    {
        "id": "ch0",
        "title": "第 0 章：先跑通一个最小闭环",
        "subtitle": "从「浏览器输入网址」到「页面显示数据」，中间到底发生了什么",
        "items": [
            {
                "id": "a01",
                "layer": "arch",
                "level": "入门",
                "title": "一次请求的完整旅程",
                "summary": "浏览器 → HTTP 请求 → 后端路由 → SQL 查询 → 数据库 → 返回 JSON → 前端渲染成 HTML",
                "points": [
                    "用户在页面上点「专业路径推荐」",
                    "前端 JS 执行 fetch('http://127.0.0.1:8765/api/recommendations/professional?student_id=20240101')",
                    "后端 FastAPI 根据 URL 找到对应的函数（路由）",
                    "函数里用 sqlite3 查询 xuetu_lite.db",
                    "数据库返回行，Python 组装成 list/dict",
                    "FastAPI 自动把 Python 对象序列化成 JSON 返回",
                    "前端拿到 JSON，用模板字符串拼成 HTML 插进 #app",
                ],
                "source": "backend/app.py:147-149 → backend/recommender.py:250-296 → frontend/app.js:115",
                "howto": "页面右侧「现场演示」区可以直接点每个环节，观察数据怎么流动",
            },
            {
                "id": "a02",
                "layer": "arch",
                "level": "入门",
                "title": "前端 / 后端 / 数据库各自负责什么",
                "summary": "三者的分工边界，搞清这个就不会迷失在代码里",
                "points": [
                    "前端（frontend/）：负责界面长什么样、用户点了什么。它不知道数据库在哪里，只会发 HTTP 请求",
                    "后端（backend/）：负责业务逻辑。它是唯一能连数据库的那一层，前端不能直接碰库",
                    "数据库（data/processed/xuetu_lite.db）：负责持久化存储，只认 SQL",
                    "推荐模型（backend/train_model.py、recommender.py）：藏在后端内部的算法层",
                ],
                "source": "frontend/ 与 backend/ 目录划分；backend/app.py:91-95 con() 是后端独有的数据库连接函数",
                "howto": "注意：整个前端目录里没有任何一处出现 SELECT 语句，这就是分层",
            },
            {
                "id": "a03",
                "layer": "arch",
                "level": "入门",
                "title": "为什么这两个服务要用两个端口",
                "summary": "主项目 8765 负责业务，learn 8766 负责教学演示，互不干扰",
                "points": [
                    "主项目：python -m uvicorn backend.app:app --port 8765（你正在运行的项目）",
                    "learn 教学服务：另一个端口 8766，只是读取项目数据做演示",
                    "learn 的 SQL 练习全部发生在副本 learn/data/learn_test.db 上",
                    "浏览器能跨端口请求，是因为后端开了 CORS",
                ],
                "source": "backend/app.py:49-54 CORSMiddleware allow_origins=['*']",
                "howto": "如果前端 demo 报 CORS 错误，说明主项目没启动",
            },
        ],
    },
    # ============================================================ 第 1 章
    {
        "id": "ch1",
        "title": "第 1 章：前端（浏览器里的 JavaScript）",
        "subtitle": "每个知识点都配一个可直接在页面里运行的 HTML 示例",
        "items": [
            {
                "id": "f01",
                "layer": "frontend",
                "level": "入门",
                "title": "页面骨架与 DOM 查询",
                "summary": "整个项目只有一个 <div id=\"app\">，所有内容都是 JS 塞进去的",
                "points": [
                    "index.html 只有 13 行：引 CSS、建 #app 容器、引 JS",
                    "document.querySelector('#app') 拿到容器，innerHTML 换掉里面的内容",
                    "这就叫 SPA（单页应用）：全程不刷新浏览器",
                ],
                "source": "frontend/index.html:10 #app 容器；frontend/app.js:16 const $ = ...；app.js:125 $/('#app').innerHTML",
                "demo": "d01-dom.html",
            },
            {
                "id": "f02",
                "layer": "frontend",
                "level": "入门",
                "title": "fetch：前端唯一需要会的请求方法",
                "summary": "fetch 一个 URL，拿到 JSON，就完成了前后端通信",
                "points": [
                    "fetch(url) 返回 Promise，要用 await 等结果",
                    "res.ok 判断状态码是否 2xx",
                    "await res.json() 把响应体解析成 JS 对象",
                    "后端抛 HTTPException 时，错误信息在 json.detail 里",
                ],
                "source": "frontend/app.js:18-26 function api(path, options)",
                "demo": "d02-fetch.html",
            },
            {
                "id": "f03",
                "layer": "frontend",
                "level": "入门",
                "title": "模板字符串渲染卡片",
                "summary": "map().join('') 三步把一堆 JSON 变成一堆 HTML",
                "points": [
                    "反引号 `` 定义多行字符串，${} 里可以写表达式",
                    "arr.map(fn) 每项变成一个 HTML 片段字符串",
                    ".join('') 拼成整段（不写 join 会出现多余的逗号）",
                    "一次性赋给 innerHTML，比逐个 createElement 快且好读",
                ],
                "source": "frontend/app.js:251-260 videoCard()；app.js:229 map(videoCard).join('')",
                "demo": "d03-template.html",
            },
            {
                "id": "f04",
                "layer": "frontend",
                "level": "进阶",
                "title": "事件绑定与事件委托",
                "summary": "给 100 张卡片各绑一次监听是错的，绑在父容器上才对",
                "points": [
                    "data-video=\"${id}\" 把数据存在 HTML 属性上",
                    "父容器只绑一次 addEventListener('click')",
                    "event.target.closest('.card') 找到被点的那张卡",
                    "card.dataset.video 读出 data-video 的值",
                    "innerHTML 重绘后监听不会失效——这是它最大的好处",
                ],
                "source": "frontend/app.js:262-269 bindVideoCards()；app.js:86-93 一键登录按钮",
                "demo": "d04-event.html",
            },
            {
                "id": "f05",
                "layer": "frontend",
                "level": "进阶",
                "title": "FormData 收集表单并 POST 提交",
                "summary": "登录表单的完整链路：收集 → POST → 处理返回 → 存状态",
                "points": [
                    "event.preventDefault() 阻止表单默认的刷新提交",
                    "new FormData(form) 自动收集所有带 name 的输入框",
                    "Object.fromEntries() 把它转成普通对象",
                    "POST 要带 method、Content-Type 头、JSON.stringify 的 body",
                ],
                "source": "frontend/app.js:94-105 登录表单 submit；后端 backend/app.py:119-125 /api/login",
                "demo": "d05-form.html",
            },
            {
                "id": "f06",
                "layer": "frontend",
                "level": "进阶",
                "title": "sessionStorage 保持登录态 + SPA 切换",
                "summary": "登录一次之后不再掉线，靠的就是浏览器本地存储",
                "points": [
                    "sessionStorage：关掉标签页就清空，适合登录态",
                    "localStorage：长期保存，除非手动清",
                    "app.js 启动时先看 sessionStorage 有没有 studentId，没有就渲染登录页",
                    "标签页切换 = 改 state.tab → 重新调 renderShell() 重绘",
                ],
                "source": "frontend/app.js:3、100、561-569；app.js:124-157 renderShell()",
                "demo": "d06-storage.html",
            },
            {
                "id": "f07",
                "layer": "frontend",
                "level": "进阶",
                "title": "async / await 异步加载与 Promise.all 并发",
                "summary": "为什么要用 await，以及怎么让它更快",
                "points": [
                    "网络请求是异步的，不等就拿不到数据",
                    "串行 await：一个接一个，总耗时是各请求之和",
                    "Promise.all：同时发，总耗时取决于最慢的那个",
                    "项目 loadApp() 用的是串行写法（app.js:114-120）",
                ],
                "source": "frontend/app.js:108-122 loadApp()",
                "demo": "d07-async.html",
            },
            {
                "id": "f08",
                "layer": "frontend",
                "level": "进阶",
                "title": "Flex / Grid 布局",
                "summary": "整个界面就靠这两个 CSS 布局撑起来",
                "points": [
                    "Flex 一维：.shell 把侧边栏和主区域横向排开（styles.css:140）",
                    "Grid 二维：.course-grid 把课程卡片铺成自适应墙（styles.css:457）",
                    "repeat(auto-fill, minmax(220px, 1fr)) 是响应式的核心写法",
                    "flex:1 表示吃掉剩余全部空间",
                ],
                "source": "frontend/styles.css:140 .shell、457 .course-grid、538 .job-grid、676 .path-row",
                "demo": "d08-cssgrid.html",
            },
            {
                "id": "f09",
                "layer": "frontend",
                "level": "实战",
                "title": "CSS 变量与动效",
                "summary": "每门课封面颜色都不一样，靠的是把数据库里的颜色写进 CSS 变量",
                "points": [
                    ":root 定义全局设计变量（配色、圆角）",
                    "行内 style=\"--cover:#884df0\" 把变量传进元素",
                    "样式表里 background: var(--cover) 取用",
                    "animation-delay: calc(var(--i) * 70ms) 做卡片依次入场",
                    "transition 让 hover 抬升平滑而非瞬变",
                ],
                "source": "frontend/app.js:191 style=\"--cover:...;--i:...\"；styles.css:476 .cover；app.js:28-34 toast()",
                "demo": "d09-cssvar.html",
            },
            {
                "id": "f10",
                "layer": "frontend",
                "level": "实战",
                "title": "埋点：用户行为如何回到推荐系统",
                "summary": "看懂这个例子，就明白了「数据闭环」四个字",
                "points": [
                    "点击卡片 → POST /api/track → 后端写 behavior_log 表",
                    "模型再从 behavior_log 算「平台偏好」特征",
                    "前端的一次点击，最终会影响下一次推荐结果",
                    "这就是完整的采集 → 训练 → 预测闭环",
                ],
                "source": "frontend/app.js:262-269；backend/app.py:167-175 /api/track；backend/train_model.py:127-138",
                "demo": "d10-track.html",
            },
        ],
    },
    # ============================================================ 第 2 章
    {
        "id": "ch2",
        "title": "第 2 章：后端（FastAPI 写的 Web 服务）",
        "subtitle": "每个接口都能在线填入参数、直接发请求、看到真实返回",
        "items": [
            {
                "id": "b01",
                "layer": "backend",
                "level": "入门",
                "title": "路由：URL 怎么找到对应的函数",
                "summary": "@app.get('/xxx') 装饰器把 URL 和函数绑在一起",
                "points": [
                    "@app.get 处理浏览器地址栏访问，@app.post 处理表单/数据提交",
                    "同一个 URL 可以用不同方法定义多个函数",
                    "FastAPI 自动生成接口文档：/docs",
                ],
                "source": "backend/app.py:104 @app.get('/')、119 @app.post('/api/login')",
                "api": {"method": "GET", "path": "/health", "desc": "最简单的一个接口，返回服务状态"},
            },
            {
                "id": "b02",
                "layer": "backend",
                "level": "入门",
                "title": "查询参数：?student_id=xxx 这部分",
                "summary": "函数参数写成普通 Python 参数，FastAPI 自动从 URL 的 ? 后面取值",
                "points": [
                    "def professional(student_id: str = '20240101', filter: str = 'all')",
                    "带默认值就是可选参数，不带就会缺失则报 422",
                    "类型注解不是摆设：FastAPI 用它做校验和文档",
                ],
                "source": "backend/app.py:147-149 professional()",
                "api": {"method": "GET", "path": "/api/recommendations/professional",
                       "params": {"student_id": "20240101", "filter": "all"},
                       "desc": "专业路径推荐，filter 可填 studying/advanced/vacation"},
            },
            {
                "id": "b03",
                "layer": "backend",
                "level": "入门",
                "title": "路径参数：把变量写进 URL 里",
                "summary": "/api/profile/{student_id} 这种花括号形式",
                "points": [
                    "{student_id} 会被 FastAPI 提取出来当函数参数传进去",
                    "适合表达「资源层级」：某个学生、某个视频",
                    "/api/videos/{video_id}/progress 是典型的 REST 风格",
                ],
                "source": "backend/app.py:137-139 /api/profile/{student_id}；app.py:178 /api/videos/{video_id}/progress",
                "api": {"method": "GET", "path": "/api/profile/20240101", "desc": "学生画像：基本信息+培养方案+成就+学习记录"},
            },
            {
                "id": "b04",
                "layer": "backend",
                "level": "进阶",
                "title": "Pydantic 请求体：POST 的 JSON 怎么接收",
                "summary": "定义一个继承 BaseModel 的类，FastAPI 自动解析并校验 JSON body",
                "points": [
                    "class LoginPayload(BaseModel): student_id: str; password: str",
                    "函数里直接 payload.student_id 取值",
                    "字段类型和是否必填都会自动校验，错了返回 422",
                ],
                "source": "backend/app.py:67-70 LoginPayload；app.py:119-125 login()",
                "api": {"method": "POST", "path": "/api/login",
                       "body": {"student_id": "20240101", "password": "123456"},
                       "desc": "登录接口，返回 token 和学生信息"},
            },
            {
                "id": "b05",
                "layer": "backend",
                "level": "进阶",
                "title": "错误处理：HTTPException",
                "summary": "出错时抛异常，前端拿到的 json.detail 就是提示文字",
                "points": [
                    "raise HTTPException(status_code=401, detail='学号或密码错误')",
                    "401 未登录/鉴权失败、404 资源不存在、422 参数不合法",
                    "前端 app.js:23 会读 await res.json() 的 detail 弹提示",
                ],
                "source": "backend/app.py:97-101 row_or_404()；app.py:124 登录失败；frontend/app.js:23",
                "api": {"method": "GET", "path": "/api/profile/99999999",
                       "desc": "故意传一个不存在的学号，看 404 长什么样"},
            },
            {
                "id": "b06",
                "layer": "backend",
                "level": "进阶",
                "title": "数据库连接与 Row factory",
                "summary": "后端每次请求都要新建一个连接，用完关掉",
                "points": [
                    "con.row_factory = sqlite3.Row 让每行能按列名取值",
                    "查不到时返回 None，要判空后抛 404",
                    "项目里每个接口都是：连库 → 查 → 转 dict → 返回",
                ],
                "source": "backend/app.py:91-95 con()；backend/recommender.py:15-22 connect() / rows()",
                "api": {"method": "GET", "path": "/api/demo-accounts", "desc": "读取 5 个演示账号的学习概况"},
            },
            {
                "id": "b07",
                "layer": "backend",
                "level": "实战",
                "title": "UPSERT：写入接口的正确写法",
                "summary": "同一个学生看同一门课的进度只能有一条，重复提交要覆盖而不是报错",
                "points": [
                    "INSERT ... ON CONFLICT(student_id, video_id) DO UPDATE SET ...",
                    "excluded.xxx 指的是「本来要插入的那个值」",
                    "写完必须 con.commit()，否则不落盘",
                    "看完全集还要往 achievement 表插成就、给学生加经验值",
                ],
                "source": "backend/app.py:178-207 /api/videos/{video_id}/progress",
                "api": {"method": "POST", "path": "/api/videos/V002/progress",
                       "body": {"student_id": "20240101", "episode_no": 6},
                       "desc": "更新学习进度，注意这会真的修改正式库数据"},
            },
            {
                "id": "b08",
                "layer": "backend",
                "level": "实战",
                "title": "中间件与静态资源托管",
                "summary": "请求进来前先过一道中间件；HTML/CSS/JS 由后端直接发给浏览器",
                "points": [
                    "@app.middleware('http') 可以在每个响应上加响应头",
                    "app.mount('/static', StaticFiles(...)) 把 frontend 目录暴露出去",
                    "FileResponse 让路由直接返回一个文件（这里是 index.html）",
                    "所以 index.html 里才能用 /static/app.js 这种路径",
                ],
                "source": "backend/app.py:57-64 中间件与 StaticFiles；app.py:104-111 FileResponse；frontend/index.html:7,11",
                "api": {"method": "GET", "path": "/", "desc": "返回主页面 HTML"},
            },
            {
                "id": "b09",
                "layer": "backend",
                "level": "实战",
                "title": "启动时的幂等初始化（bootstrap）",
                "summary": "为什么这个项目「什么都不用准备，直接跑就能用」",
                "points": [
                    "bootstrap() 在模块加载时就执行一次",
                    "数据库不存在 → 写种子文件 → 建表导入",
                    "确保额外的表和字段存在（ensure_live_schema）",
                    "补齐 5 个演示账号画像（ensure_student_profiles）",
                    "模型文件缺失或过期 → 自动重训",
                ],
                "source": "backend/app.py:30-47 bootstrap()",
                "api": {"method": "GET", "path": "/health", "desc": "db/model 两个 true 就说明初始化到位了"},
            },
            {
                "id": "b10",
                "layer": "backend",
                "level": "实战",
                "title": "SSO 免登录：HMAC 签名校验",
                "summary": "不用密码也能登录的原理——用共享密钥算签名",
                "points": [
                    "hmac.new(密钥, f'{学号}:{时间戳}'.encode(), sha256) 算出签名",
                    "URL 带上 ts 和 sig，后端用同样的算法算一遍比对",
                    "hmac.compare_digest 是定长时间比较，防时序攻击",
                    "时间戳还能用来判断链接是否过期",
                ],
                "source": "backend/app.py:27 SSO_SECRET；app.py:128-134 /api/sso",
                "api": {"method": "GET", "path": "/api/sso",
                       "params": {"student_id": "20240101", "ts": "1700000000", "sig": "错误的签名"},
                       "desc": "故意传错签名，观察 401 返回"},
            },
            {
                "id": "b11",
                "layer": "backend",
                "level": "实战",
                "title": "管理类接口：重训模型、重建画像、评估",
                "summary": "这些接口把「算法能力」也包装成了 HTTP 服务",
                "points": [
                    "POST /api/admin/evaluate —— 重新算离线指标",
                    "POST /api/admin/rebuild-profiles —— 重建 5 专业画像并重训",
                    "POST /api/admin/collect-live —— 真实联网采集（耗时较长）",
                    "GET /api/admin/data-quality —— 数据来源与覆盖率报告",
                ],
                "source": "backend/app.py:224-264 管理接口群",
                "api": {"method": "GET", "path": "/api/admin/model-report",
                       "desc": "返回训练报告：样本数、正样本率、AUC、8 个特征名"},
            },
            {
                "id": "b12",
                "layer": "backend",
                "level": "实战",
                "title": "⚠️ 源码里的一处真实缺陷（练手写 └分析能力）",
                "summary": "train_model.py 的 main() 调用了一个不存在的函数",
                "points": [
                    "train_model.py:314 写的是 bundle = train_rank_model()",
                    "但文件里实际定义的函数名是 train_fold_model（train_model.py:245）",
                    "两者名字对不上，单独执行 python -m backend.train_model 会抛 NameError",
                    "之所以平时没炸：模型文件已存在且未过期，bootstrap() 不会走到重训分支",
                    "修复很简单：把调用改成 train_fold_model()，或者加个别名",
                ],
                "source": "backend/train_model.py:313-320 main()；对比 train_model.py:245 train_fold_model",
                "howto": "这是很好的练手素材：读懂为什么平时不报错，以及修复的最小改动是什么",
            },
        ],
    },
    # ============================================================ 第 3 章
    {
        "id": "ch3",
        "title": "第 3 章：数据库（SQLite）",
        "subtitle": "在一张和正式库结构相同的副本上随便练，随时可以重置",
        "items": [
            {
                "id": "d01",
                "layer": "database",
                "level": "入门",
                "title": "13 张表分别装什么",
                "summary": "先认表，再谈 SQL",
                "points": [
                    "student 学生、course 培养方案课程、video 视频课程、video_episode 每一集",
                    "learning_record 学习进度、achievement 通关成就、behavior_log 行为埋点",
                    "recommend_log 推荐曝光与点击（训练样本的标签来源）",
                    "job 招聘岗位、skill_course_map 技能到课程的映射、exam_subject 考研科目",
                    "collection_run / collector_state 采集任务的执行记录",
                ],
                "source": "backend/data_acquisition.py:167-273 建表语句；backend/live_collectors.py 里的 ensure_schema",
                "sql_demo": {"id": "pragma-tables"},
            },
            {
                "id": "d02",
                "layer": "database",
                "level": "入门",
                "title": "主键、外键与一对多关系",
                "summary": "video.course_id 指向 course.course_id，这就是外键",
                "points": [
                    "PRIMARY KEY 唯一标识一行，不能重复也不能为空",
                    "FOREIGN KEY 保证被引用的一方一定存在（比如视频不能挂在不存在课程下）",
                    "learning_record 用 (student_id, video_id) 复合主键：一人一课只能一条进度",
                    "项目建表时写了 FOREIGN KEY，运行时靠 PRAGMA foreign_keys ON 启用",
                ],
                "source": "backend/data_acquisition.py:169-229 各表定义；data_acquisition.py:166 PRAGMA foreign_keys",
                "sql_demo": {"id": "pragma-table"},
            },
            {
                "id": "d03",
                "layer": "database",
                "level": "入门",
                "title": "SELECT 基础：取列、过滤、排序、限制",
                "summary": "SQL 最常说的四句话",
                "points": [
                    "SELECT 列 FROM 表 —— 要哪些字段",
                    "WHERE 条件 —— 只要满足条件的行",
                    "ORDER BY 列 DESC —— 排序",
                    "LIMIT n —— 只要前 n 条（数据量大的时候很重要）",
                ],
                "source": "backend/recommender.py:114-123；backend/data_acquisition.py:216-222",
                "sql_demo": {"id": "select-all"},
            },
            {
                "id": "d04",
                "layer": "database",
                "level": "进阶",
                "title": "JOIN：多表关联",
                "summary": "关系型数据库的精髓——把信息拆成多表存，查询时再拼起来",
                "points": [
                    "video 表只存 course_id，课程名要去 course 表拿",
                    "JOIN ... ON 指定拼接条件",
                    "LEFT JOIN 即使右边没匹配也保留左边的行",
                    "给表起别名 v / c 能大幅缩短 SQL",
                ],
                "source": "backend/student_profiles.py:305-309；backend/train_model.py:129-136",
                "sql_demo": {"id": "join"},
            },
            {
                "id": "d05",
                "layer": "database",
                "level": "进阶",
                "title": "GROUP BY 与聚合函数",
                "summary": "COUNT / AVG / SUM / MAX 配合分组统计",
                "points": [
                    "GROUP BY 把相同值的行归为一组",
                    "COUNT(*) 数行数，AVG() 求平均",
                    "HAVING 对分组后的结果再过滤（WHERE 是分组前过滤行）",
                    "项目用 GROUP BY platform 统计学生常逛哪个平台",
                ],
                "source": "backend/train_model.py:127-138 platform_pref 的计算",
                "sql_demo": {"id": "group-by"},
            },
            {
                "id": "d06",
                "layer": "database",
                "level": "进阶",
                "title": "子查询与 LIKE 模糊匹配",
                "summary": "项目里做关键词召回就靠这两样",
                "points": [
                    "子查询：内层先算出一个结果，外层当条件用",
                    "LIKE '%关键词%'：% 代表任意长度字符",
                    "课程的 prerequisites 用逗号分隔存多个先修课编号，用 LIKE 判断是否包含",
                    "注意：这种模式不适合高频查询，正规做法是拆成关联表",
                ],
                "source": "backend/recommender.py:85,169 prerequisites LIKE ?；recommender.py:404 title LIKE ?",
                "sql_demo": {"id": "like"},
            },
            {
                "id": "d07",
                "layer": "database",
                "level": "写入",
                "title": "INSERT / UPDATE / DELETE 三件套",
                "summary": "改数据的三条语句，每条都要小心",
                "points": [
                    "INSERT INTO 表 (列) VALUES (值)",
                    "UPDATE 表 SET 列=值 WHERE 条件 —— 忘了 WHERE 会改全表！",
                    "DELETE FROM 表 WHERE 条件 —— 同样不能忘 WHERE",
                    "写完一定要 COMMIT",
                ],
                "source": "backend/data_acquisition.py:276-309；backend/app.py:185-207；backend/student_profiles.py:255-258",
                "sql_demo": {"id": "insert"},
            },
            {
                "id": "d08",
                "layer": "database",
                "level": "写入",
                "title": "UPSERT 与事务",
                "summary": "两个让数据不会出错的关键机制",
                "points": [
                    "ON CONFLICT DO UPDATE：主键冲突时改走更新分支",
                    "excluded.xxx 引用「本来想插入的值」",
                    "事务：commit 提交、rollback 回滚，保证多步操作要么全成要么全不成",
                    "项目用事务保证「写进度 + 加经验值」不会只完成一半",
                ],
                "source": "backend/app.py:185-195 UPSERT；backend/student_profiles.py:148-158",
                "sql_demo": {"id": "upsert"},
            },
            {
                "id": "d09",
                "layer": "database",
                "level": "实战",
                "title": "还原推荐系统里的三条真实 SQL",
                "summary": "看看「召回」在数据层面到底做了什么",
                "points": [
                    "按 status='studying' 找当前在学的课，再取其视频",
                    "用 prerequisites LIKE 找出已学课程的后续课",
                    "统计学生各平台行为次数，得到平台偏好",
                ],
                "source": "backend/recommender.py:77-92,104-123；backend/train_model.py:127-138",
                "sql_demo": {"id": "real-recall"},
            },
            {
                "id": "d10",
                "layer": "database",
                "level": "实战",
                "title": "后端如何操作数据库（在线写代码）",
                "summary": "亲自写 Python 连数据库，看每一步发生了什么",
                "points": [
                    "connect → execute → commit → close 的四步流程",
                    "参数化查询 ? 占位符，绝不用字符串拼接",
                    "row_factory=sqlite3.Row 让结果可以按列名取值",
                    "最后复刻一个「接口函数」：取参数→查库→组装 JSON",
                ],
                "source": "backend/app.py:91-101；backend/recommender.py:15-22",
                "code_demo": {"id": "basic-connect"},
            },
        ],
    },
    # ============================================================ 第 4 章
    {
        "id": "ch4",
        "title": "第 4 章：推荐系统",
        "subtitle": "同一个任务，用 7 种由简到繁的方案各做一遍，横向对比指标",
        "items": [
            {
                "id": "r01",
                "layer": "recommend",
                "level": "入门",
                "title": "推荐系统到底在解决什么问题",
                "summary": "从 116 门课里，给某个学生挑出最合适的 9 门",
                "points": [
                    "候选太多（全量打分太贵）→ 先「召回」缩小范围",
                    "再「排序」给候选项打分排队",
                    "最后「重排」做多样性和业务规则调整",
                    "评估：Precision@5 / Recall@5 / NDCG@5 / HitRate@5 / 覆盖率 / 多样性",
                ],
                "source": "backend/recommender.py:250-296 recommend_professional() 就是这条流水线",
                "howto": "在页面右侧切换模型，观察指标怎么一步步变好",
            },
            {
                "id": "r02",
                "layer": "recommend",
                "level": "入门",
                "title": "Baseline：热度榜与评分榜",
                "summary": "最笨但最重要的参照物——后面的模型都得打得过它",
                "points": [
                    "所有人看到的结果完全一样，没有任何个性化",
                    "它的价值是提供一条及格线",
                    "项目把「热门」当作兜底召回的最后一路",
                ],
                "source": "backend/recommender.py:114-123 热门兜底召回",
                "model_key": "popularity",
            },
            {
                "id": "r03",
                "layer": "recommend",
                "level": "进阶",
                "title": "多路召回：把「你是谁」用起来",
                "summary": "正在学的课 → 同课视频；学过的课 → 后继课；下学期要学的 → 预习",
                "points": [
                    "学生选课有强先后顺序，这是本项目的领域知识",
                    "reasons 字典实现了「去重 + 保序」：先召回的路优先级更高",
                    "每个候选都带一句推荐理由，解释性极强",
                ],
                "source": "backend/recommender.py:67-126 professional_candidates()",
                "model_key": "curriculum",
            },
            {
                "id": "r04",
                "layer": "recommend",
                "level": "进阶",
                "title": "TF-IDF 内容相似度",
                "summary": "把课程描述变成向量，解决「新课没人学过」的冷启动问题",
                "points": [
                    "分词：英文数字走正则，中文单字 + 二元组（没用 jieba）",
                    "TF-IDF 权重：(1 + log tf) * idf",
                    "L2 归一化后，余弦相似度就等于向量点积",
                    "新课只要有文字介绍，立刻能被推荐出去",
                ],
                "source": "backend/train_model.py:23-49 tokenize / build_tfidf",
                "model_key": "tfidf",
            },
            {
                "id": "r05",
                "layer": "recommend",
                "level": "进阶",
                "title": "ItemCF 协同过滤",
                "summary": "看你学过什么，找「和它被同一批人喜欢」的课",
                "points": [
                    "离线算出课与课的相似度表，线上直接查",
                    "和内容相似度互补：前者看「像不像」，后者看「行为相不相关」",
                    "相似度表在项目里被训练脚本存进 ranker_model.json",
                ],
                "source": "backend/train_model.py:58-69 build_item_similarity；recommender.py:93-96 在线使用",
                "model_key": "itemcf",
            },
            {
                "id": "r06",
                "layer": "recommend",
                "level": "实战",
                "title": "特征工程：8 维特征向量",
                "summary": "把一门课「值不值得推给某个学生」量化成一个向量",
                "points": [
                    "log_popularity：热度取对数，压缩量级差异",
                    "rating：评分",
                    "free_access：免费与否（学生很在意）",
                    "curriculum_graph：与培养方案/先修关系的契合度",
                    "itemcf_similarity：和历史看过的课的相似度",
                    "platform_preference：平台偏好（由 behavior_log 统计）",
                    "course_downstream_value：这门课是几门课的先修",
                    "major_alignment：专业匹配度",
                ],
                "source": "backend/train_model.py:105-156 feature_vector()；配合 app.py:292-301 特征名列表",
                "model_key": "logistic",
            },
            {
                "id": "r07",
                "layer": "recommend",
                "level": "实战",
                "title": "逻辑回归排序模型",
                "summary": "不用 sklearn，纯手写梯度下降——每一步都看得见",
                "points": [
                    "z-score 标准化：让各特征在同一量纲上比较",
                    "p = sigmoid(w·x + b) 输出点击概率",
                    "L2 正则防止过拟合",
                    "AUC 衡量排序能力：随机挑正负样本，正样本分更高的概率",
                ],
                "source": "backend/train_model.py:159-210 sigmoid / train_logistic / auc",
                "model_key": "logistic",
            },
            {
                "id": "r08",
                "layer": "recommend",
                "level": "实战",
                "title": "多目标融合与 MMR 多样性重排",
                "summary": "最后两步让结果「好用」而不只是「准」",
                "points": [
                    "融合：0.62*模型分 + 0.20*召回理由 + 0.12*课程质量 + 0.06*免费加成",
                    "MMR：惩罚与已选项目相似的候选，避免 9 条全是同类内容",
                    "平台打散：同一个平台出现多次就扣分",
                    "这一步牺牲一点精度，换来明显更好的使用体验",
                ],
                "source": "backend/recommender.py:220-240 mmr_rerank；recommender.py:284-296 融合公式",
                "model_key": "full",
            },
        ],
    },
]


def search(keyword: str) -> List[Dict[str, Any]]:
    """按关键字检索知识点（标题、摘要、要点、出处都参与匹配）。"""
    kw = (keyword or "").strip().lower()
    if not kw:
        return []
    hits = []
    for chapter in CHAPTERS:
        for item in chapter["items"]:
            haystack = " ".join([
                item.get("title", ""),
                item.get("summary", ""),
                item.get("source", ""),
                " ".join(item.get("points", [])),
            ]).lower()
            if kw in haystack:
                hits.append({**item, "chapter": chapter["title"]})
    return hits
